### ISSUE TITLE
Required Casino Chips - Continues to stay on screen after pressing escape. 

### ISSUE THREAD

**Issue by MisfitButter** [ianvalls90/qb-slots#1]
Basically, when you click to Play Slots and instead of inputting a value, you press escape to exit. The Required Casino Chips stay's on the client's screen forever.

**Comment by ianvalls90** [comment]
will be fixing this in about 1 or 2 hours.

**Comment by ianvalls90** [comment]
Fixed, redownload or update NET EVENTS part on client.lua
